services:
  angular-app:
    image: frontend-mspr
    container_name: frontend-mspr
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:4200"
    restart: unless-stopped
    tty: true
